const FPS = 30;
const CANVAS_ID = 'game-window';
const CANVAS_WIDTH = 400;
const CANVAS_HEIGHT = CANVAS_WIDTH;
const PART_WIDTH = 10;

let INITIAL_GAME_SPEED = 500;
const GAME_SPEED_DELTA = 25;
const GAME_SPEED_LIMIT: number = 75;

export { FPS, CANVAS_ID, CANVAS_WIDTH, CANVAS_HEIGHT, PART_WIDTH, INITIAL_GAME_SPEED, GAME_SPEED_DELTA, GAME_SPEED_LIMIT };
